[workspace]
members = ["phonetics-html"]
resolver = "2"


[workspace.dependencies]
plotters = "0.3"
rust_tokenizers = "8.1"
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "1.1"
regex = "1.10.5"

